# Generated by Django 5.1.6 on 2025-02-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
