# Generated by Django 5.1.6 on 2025-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_friendrequest_is_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_delivered',
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
