# Generated by Django 5.1.6 on 2025-02-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_friendrequest_is_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatemessage',
            old_name='content',
            new_name='message',
        ),
    ]
